name: Build HMA++

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential make

    - name: Compile project
      run: make

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: HMAPlus-build
        path: "*.kpm"
