name: Cross-Compile ARM64 KPM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 升级到 v4 版本

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          autoconf \
          automake \
          libtool \
          linux-headers-generic \
          libssl-dev \
          git \
          gcc-aarch64-linux-gnu \
          binutils-aarch64-linux-gnu

    - name: Configure cross-compiler
      run: |
        echo "TARGET_COMPILE=/usr/bin/aarch64-linux-gnu-" >> $GITHUB_ENV

    - name: Compile project
      run: |
        make clean
        make

    - name: Upload artifact (已升级到 v4)
      uses: actions/upload-artifact@v4
      with:
        name: hmaplus-arm64-kpm
        path: ./HMA++.kpm
    - name: Compile project
      run: |
        make clean
        make  # 直接调用 Makefile，使用环境变量中的工具链

    - name: Upload artifact (升级到 v4)
      uses: actions/upload-artifact@v4  # 替换为 v4 版本
      with:
        name: hmaplus-arm64-kpm
        path: ./HMA++.kpm
    - name: Compile project
      env:
        TARGET_COMPILE: /usr/bin/aarch64-none-elf-
      run: |
        make clean
        make

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: hmaplus-arm64-kpm
        path: ./HMA++.kpm
