name: Cross-Compile ARM64 KPM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          autoconf \
          automake \
          libtool \
          linux-headers-generic \
          libssl-dev \
          git

    - name: Setup cross-compiler
      uses: actions/setup-cross-compiler@v1
      with:
        compiler: aarch64-none-elf-gcc
        target: aarch64-none-elf
        arch: arm64
        triplet: aarch64-none-elf

    - name: Compile project
      env:
        TARGET_COMPILE: /usr/bin/aarch64-none-elf-
      run: |
        make clean
        make

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: hmaplus-arm64-kpm
        path: ./HMA++.kpm
